### ISSUE TITLE
Publish 1.11.2 Version

### ISSUE THREAD

**Issue by renevo** [Impelon/Disenchanter#10]
I see there is a branch for it, any chance on publishing it?

I could build it myself from source and use it on my private server, just didn't want to 📦

**Comment by Impelon** [comment]
Same here =p

I'm currently quite busy, and actually wanted to update the mod to add a few requests and new things, but as you may be able to tell: I have not gotten around to it. So either you have the patience to wait another month or so when I'll do the update or you build it against 1.11.2 yourself, because I'd have to go through the same kind of steps as you. I have not even got the 1.11.2-forge installed on my PC yet.

**Comment by renevo** [comment]
Sounds good, thanks for reply!

**Comment by Impelon** [comment]
Official Release btw. ^^
