### ISSUE TITLE
HomeServer Crash Disenchanter 1.5 (MC1.7.10)

### ISSUE THREAD

**Issue by kellixon** [Impelon/Disenchanter#18]
[fml-server-latest.log.txt](https://github.com/Impelon/Disenchanter/files/989106/fml-server-latest.log.txt)
[crash-2017-05-10_11.05.31-server.txt](https://github.com/Impelon/Disenchanter/files/989108/crash-2017-05-10_11.05.31-server.txt)
MC1.7.10, Forge 10.13.4.1614.

**Comment by Impelon** [comment]
Sooo... At first I thought it might be because of me being lazy with updating my local Forge version (using 10.13.3.1399 for 1.7.10 yea xD)
I've updated to 10.13.4.1558 (the recommended build for 1.7.10) and I havn't got any errors... I'll update the modfile on curse eitherway. Maybe it helps? 
I'll look a bit more into it, but I really have no idea why your crash happens. Apparently the field "top" is missing, but this is a private IIcon attribute. Your error should never happen except the file is corrupted or something. I don't know. Maybe you have an Idea? 
**I think first of all you should try it with the new file on curse.**

**Comment by kellixon** [comment]
Sorry, I have no ideas. Clear server, only Forge and Mod. In the client everything works fine, the only problem on the server.
forge-1.7.10-10.13.4.1558-1.7.10-installer-win
DisenchanterMod-[1.7.10]1.5.jar
[fml-server-latest.log.txt](https://github.com/Impelon/Disenchanter/files/992206/fml-server-latest.log.txt)
[crash-2017-05-11_10.43.47-server.txt](https://github.com/Impelon/Disenchanter/files/992207/crash-2017-05-11_10.43.47-server.txt)

**Comment by Impelon** [comment]
Hm.. okey then it's probably an oversigth on my part, sorry for that. I'll get around to fix that then.

**Comment by Impelon** [comment]
Ok, yep found the problem. Thankfully this is only in the 1.7.10 version. In the 1.5 update I've changed a few things around internally, also regarding textures. It seems I can't initialize an attribute in the class if it's SideOnly.Client; what a shame =p (Now saying this it makes sense, but it isn't obvious to me) 

I'll fix this and update the curse file again!

**Comment by Impelon** [comment]
Updated the Curse File again. Should hopefully work now. 
Again: Sorry, this was a ridiculously small mistake. Would be nice of you, if you'd tell me if everything works now. If there are any other issues you experience regarding the mod, I'm happy to help ^^

**Comment by kellixon** [comment]
Yes! Now everything works fine. There are no errors. Thank you very much for the mod.
