### ISSUE TITLE
[1.12.2] Breaks Buildcraft's oil texture.

### ISSUE THREAD

**Issue by brisingraerowing** [Impelon/Disenchanter#24]
As per title. Might be related to #12

**Comment by Impelon** [comment]
Yeah, probably similar to #22 aswell... 
I _should_ get around to fix this, but I have too little time and motivation to work on this at the moment. I'm terribly sorry =I

**Comment by brisingraerowing** [comment]
It's fine. I'm not using this mod all that much right now. I don't play worlds for very long (and I play in creative most of the time), so I'm just going to install DE. I still like how this mod is automatable, but I also like that DE allows you to choose which enchantment to remove (and supports stacking plain books in their respective input slot).

**Comment by Impelon** [comment]
Actually working on this now and it seems to me this is an issue on buildcraft's side, too.
In the newer version of buildcraft this is fixed. But in the older version, two of the 3 oil variants have the missing textures __with just optifine__ (not my Mod) installed. 
I'm trying to come up for a good solution for #12, but to be honest, I think if my mod conflicts somehow with another mod texturewise it means be __both__ do something wrong.

**Comment by Impelon** [comment]
Actually, this seems to have been mostly an issue on their part, not mine. Atleast I tried with a version that does not conflict with the other mods (LootBags for example worked fine), but BuildCraft's Oil is bugged out completely... Whatever it's fixed in a newer buildcraft version anyways, I've found a solution for the other texture-problems, so I don't expect this to come up again.

**Comment by Impelon** [comment]
The fix for all the other issues is coming in just a few minutes... I'm closing this, since I don't think there is anything there is to do about this, this issue is with Buildcraft IMHO.
