### ISSUE TITLE
Hoppers pull items out of first slot preventing automation.

### ISSUE THREAD

**Issue by nitefang** [Impelon/Disenchanter#35]
Vanilla hoppers will pull items from the first slot and the last (output) slot. This means it is impossible to automate a set up efficiently as the hopper will pull the enchanted item out of the table before it can have the enchantment removed.

**Comment by Impelon** [comment]
This is also needed, because one needs to be able to extract the first item after the disenchantment-process is finished. I agree, that makes it hard to automate it purely in vanilla, though by all means not impossible, you just have to get a bit creative with a redstone locking mechanism to lock the extracting-hopper until the process is finished. 
The automatic version _does_ produce a comparator output if you hook one up, maybe that can help.

Maybe I could make a tutorial/template for a working system?
