### ISSUE TITLE
Auto Disenchanter Stops Working In System

### ISSUE THREAD

**Issue by mryosupman** [Impelon/Disenchanter#44]
Hello, so, I'm not sure if anyone else has encountered this issue, but I've actually managed to get a redstone contraption set up which feeds in multi-enchanted books and then regular books, with a locking mechanism on the output hopper to allow for ample time for the disenchant to take place, but for some reason it just breaks the table. 
   
   If I plop an auto table down on the ground and fill it manually, it works repeatedly and the cooldown is much, much faster than the current timing on my clock. However, when I place the table on top of a locked hopper and in between two droppers, it works fine for the first book and then breaks for the second. Nothing I can do after will let it disenchant again, even if I do fill it manually. 

   I understand this is a very specific and individual situation, but at the same time I feel like I'm not the only one who'd like to use these tables in this sort of a set-up. Has anyone else encountered this issue or found a workaround, or do you have any thoughts yourself, Impelon?

EDIT: It also seems to allow one disenchant upon loading the world or reloading the chunk, but then it breaks again. Not sure if this is helpful or relevant, but I know in these situations more information is usually better. Speaking of more information, my version is 1.12.2

EDIT 2: I'm adding this to the main post because it seems like it's the type of thing that would be better here than just in a comment. It seems to be the hopper that's the issue, maybe the table itself isn't qualifying that as an empty state? Like, when it's first loaded it sees the output slot as empty, but it doesn't see it as empty again until it's either reloaded or the item is taken out manually. I can use this as a workaround for now, but hopefully this narrows it down for when you get the chance to take a look at it. Attaching a comparator to the table gives no signal, so the game does realize the table is empty, but for whatever reason it either stops disenchanting after the first or thinks it can't, because nothing I do, not even removing the hopper will make the table work again besides reloading the world or the chunk. It does work consistently if I remove the hopper and reload the chunk.

**Comment by Impelon** [comment]
Gosh, I hate you let you guys down...
So I guess this is not related to the other issues regarding automation?
I'm currently quite unable to work on the mod (or test bugs)... Maybe over
the holidays? That is not a promise, tho.
Again, I'm sorry... I'll what I can do.

**Comment by mryosupman** [comment]
I only just downloaded the mod today, I certainly don't mind waiting for a solution. I realized that I do have a few other mods installed which could be causing compatibility issues, but I just assumed that since I wasn't using any of those mods' mechanics or components it shouldn't be affecting it. I'll do some testing without the mods installed later and see if I get different results, just to be completely sure. I don't think it's related to the other issues that are there, as the table itself is failing to disenchant the book. When I do my other tests I'll also see how it behaves if I use items instead of books

**Comment by mryosupman** [comment]
So it behaved the same when I tested it with this mod as the only one installed and in a fresh world, and it does the same thing with items, so it's not just an issue with enchanted books. If there's anything else you could think of that you'd like me to test for you, just let me know, I'll be happy to help out however I can.

**Comment by borkmaster** [comment]
I've also experienced the same issue. A suggestion: if the table only allowed items to exit into the hopper from its output slot, instead of the way it currently works (items exit from both the first input slot and the output slot), an elaborate redstone setup wouldn't be necessary to try and use the automatic disenchanting table in an automated fashion.

It would also be nice if the device registered as having an inventory, so other mods' item transfer utilities could be used on the device. As of right now, the only way to extract items from the block is to use hoppers, which makes it impossible to use the device, even if you lower the "how many ticks should the automatic disenchantment process last" config option, down to 0 or 1 (the config option doesn't seem to change the time to disenchant at all). There is currently no way that I could find to use the automatic disenchanting table in a manner that doesn't require you to manually move items into and out of the device inventory, rendering the "automatic" utility of the disenchanting table virtually meaningless.

**Comment by borkmaster** [comment]
Any time you remove an item-accepting hopper from under the disenchanter by any means (I tested placing and breaking the hopper, temporarily turning off the hopper with a redstone signal, and moving the hopper with a piston) the disenchanter breaks as described in the original post.

**Comment by mryosupman** [comment]
As Impelon said in a comment on another post, both slots need to be able to be pulled from to make sure you can automatically take back any equipment type items in the first slot. The redstone to get the timing working is simple enough, I'm personally not concerned about having to set it up that way in game so long as it works consistently. However I can also see why people would want them to work with one output. Maybe this can be added in as a config option, or even an entirely new type of table in a future update. I can't recall if this has been mentioned elsewhere, but it might also be nice if the table could recognize and correctly place blank books or be set up to take directional inputs similar to that of a furnace. Of course going that far would depend on how much time and effort you're wanting to put into this; if the automation can be fixed then I can get all the use I could ever want out of these tables exactly how they are.

**Comment by Impelon** [comment]
Guess that the inventory not bring recognized is a consequence of me not
switching to the new Forge-Item-Management-System (forgot what it was
called). Maybe this bug is also related to that, I'd have to test this
myself in 1.7.10 and 1.12 to confirm, but I think it did work back in
1.7.10 and 1.9, when I introduced it.

That being said, yes; I must not block the pulling from the input slot. I
guess, if I had directional output tho, you could automate it easier with
pipes or similar. Another alternative would be to introduce another
output-slot, but then I would not like how you would need to manually drag
back equipment to the inputs.

So all in all, this does get me somehow excited, so I think I will work on
a new version with some bugfixes and overhauls, but that may take a while,
as I really do not have the time at the moment. (Also I need to reinstall
Forge, as I've reset my entire computer setup.)
