### ISSUE TITLE
Additional Crafting Recipes Unavailable

### ISSUE THREAD

**Issue by CSGant** [Impelon/Disenchanter#48]
Currently, while using RLCraft version 2.7.1, the Disenchantment Table is able to be crafted, but the additional recipes to modify the table's attributes are unavailable. Following the exact recipes from the crafting guide videos provided, none of them work. What's even more, is that using the JEI menu, the original crafting recipe for the Disenchantment Table can be viewed, but clicking on the table variants will not do anything and simply just show the tooltip that pops up when hovered over.

**Comment by Impelon** [comment]
I've been told the config of the disenchanter-mod was heavily modified for RLCraft; 
In fact so much, I've been getting a ton of people complaining about bugs that turned out to be just wierd configurations.

There are options to disable the individual crafting-recipes... Maybe check your config.

Hope this helps. If the issue persists, please get back to me.
