### ISSUE TITLE
About cycling mode,any plan for MC ver1.7.10?

### ISSUE THREAD

**Issue by minecraftyusei** [Impelon/Disenchanter#65]
(I am using google translate ,sorry for my english)
I found the cycling table appear only in mod ver1.7+,MC ver1.12+
any plan for MC ver1.7.10?

**Comment by Impelon** [comment]
Hey!
I am sorry, the source code for the mod changed a lot between version 1.8 and version 1.6. Also I did decide to drop support for older Minecraft versions because it was hard to work on so many versions at once.

Implementing the cycling variant for MC version 1.7.10 would be quite complicated for me, because I do not know how the code works anymore, and I unfortunately do not have the time to look into it.

Hope you understand!

**Comment by minecraftyusei** [comment]
> Hey! I am sorry, the source code for the mod changed a lot between version 1.8 and version 1.6. Also I did decide to drop support for older Minecraft versions because it was hard to work on so many versions at once.
> 
> Implementing the cycling variant for MC version 1.7.10 would be quite complicated for me, because I do not know how the code works anymore, and I unfortunately do not have the time to look into it.
> 
> Hope you understand!

sad to hear this message, but I can understand.Lets end this question.
